name: sweets-env
channels:
  - conda-forge
dependencies:
  - python>=3.7,<3.11
  - pip>=21.3  # https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/#editable-installation
  - git  # for pip install, due to setuptools_scm
  - gdal>=3.3
  - h5py>=3.6
  - numpy>=1.20
  - pydantic>=1.10
  - pyproj>=3.2
  - ruamel.yaml>=0.15
  - tqdm>=4.60

  - rich
  - rioxarray
  - dask
  - jupyter-server-proxy
  - pip:
    - git+https://github.com/opera-adt/COMPASS
    - git+https://github.com/opera-adt/s1reader
    - git+https://github.com/opera-adt/dolphin  # will this work?
