name: sweets-env
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - pip>=21.3  # https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/#editable-installation
  - git  # for pip install, due to setuptools_scm
  - aria2 # ASF Downloading
  - gdal>=3.3
  - geopandas>=0.12.0
  - h5py>=3.6
  - numpy>=1.20
  - pandas>=1.5
  - pydantic>=1.10,<2
  - requests>=2.20
  - rich>=12.0
  - rioxarray>=0.13
  - sardem>=0.11.3
  - sentineleof>=0.7.0
  - shapely>=1.8
  - dask>=2022.6.0
